### ISSUE TITLE
Support for other curves? (SECP256R1, Ed25519)

### ISSUE THREAD

**Issue by moshemalawach** [ecies/js#183]
Is support for other curves planned?
Namely SECP256R1 and Ed25519 for example?

**Comment by kigawas** [comment]
Planned. But may need some refactoring

**Comment by moshemalawach** [comment]
Any idea how I can help? :)

I am no cryptographer, but it's a feature we will clearly need to support more addresses/keys sources!

Example of product we are working on that is using this lib:
https://my-beta.aleph.im

**Comment by L11R** [comment]
@moshemalawach I guess we will have to change API slightly. As far as I remember it @kigawas's idea was to support only one safe curve to keep lib set as simple as possible. 

But `secp256k1` is not very good choice according to http://safecurves.cr.yp.to/index.html

So there are two ways:
1. Switch from `secp256k` to something like `X25519` and that's it.
2. Add support for more curves. But curves don't differ just by constants in them. `Ed25519` is a twisted Edwards curve for example. It will require some refactoring to make generic library that handles various curve types.

I personally understand why @kigawas wants to keep it as simple as it could be. I am not a crypto specialist so cannot maintain complex crypto library without proven primitives underneath.

But it still would be nice to support at least `X25519` as default and NIST group of curves as optional.

**Comment by moshemalawach** [comment]
I depend highly on it, please don't remove secp256k1 support!
Supporting other curves would be great, but we need to keep this one :)

**Comment by moshemalawach** [comment]
As for changing API to support more curve types, it totally makes sense.

**Comment by L11R** [comment]
@moshemalawach we won't remove anything I guess.

Btw why you are so bound to `secp256k1`? I see you project is related to blockchain, that's the reason?

**Comment by moshemalawach** [comment]
You can have a look at https://my-beta.aleph.im for an example of use.

We support addresses of multiple blockchains, and need to encrypt for those users and their public key :)
While some can allow for newer curves, most are bound to SECP256K1 or SECP256R1. We will add support for other blockchains soon like Tezos, Polkadot-flavored, Cosmos-flavored and others, and those support better curves.

We accept addresses, signatures and content of all those blockchains addresses on our network.

**Comment by kigawas** [comment]
The pr above will support x25519 and ed25519
