### ISSUE TITLE
Browser-friendly crypto

### ISSUE THREAD

**Issue by lastmjs** [ecies/js#259]
It would be nice to not rely on Node's crypto module, at least when in the browser. As I understand it this project is expecting the user's build tool to polyfill the node crypto library automatically. Not all build tools will do this.

**Comment by kigawas** [comment]
[Parceljs](https://parceljs.org/) looks great, but I'm not sure how to integrate it seamlessly to support both nodejs and browser.

Do you have any insight?

**Comment by kigawas** [comment]
I've released a [WASM port](https://github.com/ecies/rs-wasm) on npm. You can install it by `npm install ecies-wasm`.
