### ISSUE TITLE
Unable to resolve module crypto

### ISSUE THREAD

**Issue by vikassharma96** [ecies/js#395]
I am using this library in react native app and got this error even when navigating to the directory I was able to access the crypto module. Do I need to externally install react native crypto?

`error: Error: Unable to resolve module crypto from /Users/..../node_modules/eciesjs/dist/utils.js: crypto could not be found within the project or in these directories`

**Comment by kigawas** [comment]
Yes. You'd probably need react native crypto.
If your react native app has webview, you can also try [the wasm build](../../rs-wasm).
