### ISSUE TITLE
Go compabilites

### ISSUE THREAD

**Issue by stlr00** [ecies/js#416]
Unnable to encrypt/decrypt between GO and JS

**Comment by kigawas** [comment]
Did you mix hex string and bytes? Maybe you can check https://github.com/ecies/go/issues/17 to see whether you have the same problem

**Comment by stlr00** [comment]
We try make private and public keys at go side, then send hex public key to js and encrypt msg. After thet go try to decrypt msg with private key and it doesnt work. Of course we check all data formats compablities.

**Comment by kigawas** [comment]
Can you post the private key and public key?

**Comment by stlr00** [comment]
5b5b1a0ff51e4350badd6f58d9e6fa6f57fbdbde6079d12901770dda3b803081 its private
048e41409f2e109f2d704f0afd15d1ab53935fd443729913a7e8536b4cef8cf5773d4db7bbd99e9ed64595e24a251c9836f35d4c9842132443c17f6d501b3410d2 its public

**Comment by kigawas** [comment]
Cannot reproduce. Are you passing the right Buffer to the JS decrypt function?

**Comment by stlr00** [comment]
Of course. Tomorrow will try reproduse again and send video.

**Comment by kigawas** [comment]
> Of course. Tomorrow will try reproduse again and send video.

How large is your video? For files more than several gigabytes, aes-gcm may have problem encrypting

**Comment by stlr00** [comment]
No no. We encrypt only string. I will capture video with problem.
