### ISSUE TITLE
Issue when running eciesjs from Jest.

### ISSUE THREAD

**Issue by goncer** [ecies/js#494]
I am trying to incorporate this lib into my Jest tests, but getting the following error:
`Expected private key to be an Uint8Array`

Error trace:
```
 ./node_modules/jest/bin/jest.js ts-node/register test/sequential/test.ts 
 FAIL  test/sequential/test.ts
  test string <-> buffer utils 
    ✕ should generate valid secret (4 ms)

  ● test string <-> buffer utils  › should generate valid secret

    Expected private key to be an Uint8Array

      3 | describe("test string <-> buffer utils ", () => {
      4 |   it("should generate valid secret", () => {
    > 5 |     const key = getValidSecret();
        |                 ^
      6 |   });
      7 | });
      8 |

      at assert (node_modules/secp256k1/lib/index.js:18:20)
      at isUint8Array (node_modules/secp256k1/lib/index.js:22:3)
      at Object.privateKeyVerify (node_modules/secp256k1/lib/index.js:66:7)
      at getValidSecret (node_modules/eciesjs/dist/utils.js:25:35)
      at Object.<anonymous> (test/sequential/test.ts:5:17)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.764 s, estimated 2 s
```

I created this small test that fails,
```
import { getValidSecret } from "eciesjs/dist/utils";

describe("test string <-> buffer utils ", () => {
  it("should generate valid secret", () => {
    const key = getValidSecret();
  });
});
```
you can run it with:
`./node_modules/jest/bin/jest.js test.ts `

Jest version:
`"jest": "^26.6.3",`

when running with mocha all good :)
```
./node_modules/mocha/bin/mocha -r ts-node/register test/sequential/test.ts 
  test string <-> buffer utils 
    ✔ should generate valid secret
  1 passing (9ms)
```

hopefully, you can help me a bit :)
Thanks!

UPDATE: 
I think this is somehow reported in a lib dependency project. I'm still wondering why it works in mocha but not in JEST :upside_down_face: 
https://github.com/cryptocoinjs/secp256k1-node/issues/175

**Comment by goncer** [comment]
hey @kigawas ,
I found a way to solve it. The issue is on Jest not exporting some globals.
https://github.com/facebook/jest/issues/4422
The issue is kindly solved by exporting some globals,
https://github.com/jolocom/jolo-did-method/blob/1302227410d7aa91262e3da9ecafaaa89779b68e/jest.config.js

**Comment by kigawas** [comment]
> hey @kigawas , I found a way to solve it. The issue is on Jest not exporting some globals. [facebook/jest#4422](https://github.com/facebook/jest/issues/4422) The issue is kindly solved by exporting some globals, https://github.com/jolocom/jolo-did-method/blob/1302227410d7aa91262e3da9ecafaaa89779b68e/jest.config.js

Thank you for sharing!
