### ISSUE TITLE
Uncaught (in promise) TypeError: (0 , crypto_1.randomBytes) is not a function   

### ISSUE THREAD

**Issue by liaoyu1992** [ecies/js#547]
Uncaught (in promise) TypeError: (0 , crypto_1.randomBytes) is not a function
    at getValidSecret (utils.js:24:28)
    at new PrivateKey2 (PrivateKey.js:12:45)
![image](https://user-images.githubusercontent.com/6285162/157205852-83dd7861-4d8b-462d-9538-027248305d38.png)

**Comment by kigawas** [comment]
crypto is a node module, which is not available in browser. You may need webpack or browserify
