### ISSUE TITLE
getrRandomValues error

### ISSUE THREAD

**Issue by vincenzoiovino** [ecies/js#731]
Hello,
I get the following error when trying to run the example you show:

> decrypt(k1.toHex(), encrypt(k1.publicKey.toHex(), data)).toString()
/home/node_modules/@noble/ciphers/webcrypto/utils.js:18
    throw new Error('crypto.getRandomValues must be defined');
    ^

Uncaught Error: crypto.getRandomValues must be defined

Any clue on how to bypass it?

**Comment by kigawas** [comment]
If you are on React Native, you may need to polyfill webcrypto. 
Check https://github.com/paulmillr/noble-ciphers#usage for details

**Comment by vincenzoiovino** [comment]
No, I am not on react...
