### ISSUE TITLE
Unable to resolve "@ecies/ciphers/aes" from "node_modules/eciesjs/dist/utils/symmetric.js"

### ISSUE THREAD

**Issue by ram4444** [ecies/js#808]
Hi, I have faced an issue as shown in title when I start my react native app.
May you help to investigate the issue behind?

version in package.json
"@metamask/sdk": "^0.30.0",
"@metamask/sdk-react": "^0.30.0",
"eciesjs": "^0.4.10",

**Comment by kigawas** [comment]
I have confirmed this happens when you are using expo (`npx create-expo-app@latest`). You have to configure it to support package exports (please see https://reactnative.dev/blog/2023/06/21/package-exports-support), but it seems not that easy. 

I recommend to set up your react native project without expo to see whether the same issue happens

**Comment by ram4444** [comment]
Thanks for your reply.

For the suggestion of set up an react native project without expo, I have tried so but, I can only find the expo one works in metamask-sdk's example git (they have 3 of them one of react-native only example) (They have updated the package.json so that none of them works now unless downgrading to the version which is using "eciesjs": "0.3.20"]

[reactNative only example 1 (not work for me)](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeDemo)
[reactNative only example 2 (not work for me)](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/reactNativeSdkDemo)
[expo example(now i am working on)](https://github.com/MetaMask/metamask-sdk/tree/main/packages/examples/expo-demo)

According to the article, Package Exports will be enabled for most projects in the next React Native release (0.73) later this year. To upgrade the sample expo sample project from Metamask-sdk's git to latest react-native version (and also the expo version) I have run 
```
npx create-expo-app@latest

```
starting from the beginning and copy other files back, so that I expected package exports has already been enabled. However the same error message does happen.

By adding the line below mentioned in the article
```
config.resolver.unstable_enablePackageExports= true,
```
I am getting the error msg of 

**Android Bundling failed 8291ms node_modules/expo-router/entry.js (3338 modules)
The package at "node_modules/@ecies/ciphers/dist/_node/compat.js" attempted to import the Node standard library module "node:crypto".
It failed because the native React runtime does not include the Node standard library.**

Here is my metro.config.js
```
//const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");

// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

config.resolver.extraNodeModules = {
  ...require("node-libs-expo"),
};

config.resolver.sourceExts = ['jsx', 'js', 'ts', 'tsx', 'cjs', 'json']

config.resolver.unstable_enablePackageExports= true,

config.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: true,
  },
});

module.exports = config;
```

**Comment by kigawas** [comment]
I have added react-native exports for `@ecies/ciphers`, now it will use pure js implantation so you don't have to polyfill node modules 

https://github.com/ecies/js-ciphers/pull/3

**Comment by kigawas** [comment]
I'll also publish a react native example soon

**Comment by ram4444** [comment]
Thanks for your reply
I will refer this thread to Metamask-SDK team

**Comment by kigawas** [comment]
I've confirmed that it works on React Native with the latest version of `@ecies/ciphers` (0.2.1) when package exports enabled

**Comment by ram4444** [comment]
Please update the dependency on ecies as it is still showing 0.2.0 
![image](https://github.com/user-attachments/assets/7c750582-17f7-43c4-ad8d-0276b623be8a)

**Comment by kigawas** [comment]
No we don't have to because it's semver ^0.2.0 (>=0.2.0,<0.3.0), you can just pnpm update or yarn upgrade

**Comment by kigawas** [comment]
The react native demo is public now: https://github.com/ecies/js-rn-demo
